title: 'Port of Alsea'
default_lang: en
author:
  name: 'Port of Alsea'
  email: info@portofalsea.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
