title: 'photon âœ´ STARTER'
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
logo: photon-logo.png
