title: photon STARTER
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
  - photon
metadata:
  description: This is a template site for creating new photon WEBS
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
logo: photon-logo.png
